"""Detection-rule generator for the technique catalog.

Translates a catalog entry into a starter detection rule in one of:

  * Cortex XSIAM XQL
  * Generic Sigma (Splunk / Elastic compatible after conversion)
  * Splunk SPL

These outputs are *starter* rules — the operator copies them into XSIAM
custom analytics / SIEM, tunes the data-model field names to match their
ingestion schema, and adds severity/playbook bindings.

NOTE: The rules are derived heuristically from the test's executor and
command string. They are deliberately broad — designed to fire on the
benign telemetry the catalog emits, then be tightened by the operator.
"""
from __future__ import annotations

import re
import shlex
from dataclasses import dataclass

from .loader import Technique, TechniqueTest, get_test, list_techniques


SUPPORTED_RULE_FORMATS = ("xql", "sigma", "spl")


@dataclass(frozen=True)
class DetectionRule:
    """A generated starter detection rule."""

    technique_id: str
    test_name: str
    rule_format: str  # "xql" | "sigma" | "spl"
    title: str
    rule: str
    notes: str


# ---------- helpers ----------------------------------------------------------
_PROC_FIELDS = {
    "xql": {
        "process_name": "action_process_image_name",
        "process_cmd": "action_process_image_command_line",
        "parent_name": "actor_process_image_name",
        "user": "action_process_username",
        "host": "agent_hostname",
        "dataset": "xdr_data",
        "event_type_proc": "event_type=ENUM.PROCESS",
    },
    "spl": {
        "process_name": "process_name",
        "process_cmd": "process_cmdline",
        "parent_name": "parent_process_name",
        "user": "user",
        "host": "host",
        "dataset": "index=xdr OR index=sysmon sourcetype=*",
        "event_type_proc": "EventCode=1",
    },
}


def _extract_keywords(command: str) -> list[str]:
    """Pull distinctive tokens an analyst could match on.

    Returns lowercase, deduplicated tokens — limited to 6 to keep the
    generated query terse and tunable.
    """
    if not command:
        return []
    # Pull words long enough to be meaningful, skip obvious noise.
    raw = re.findall(r"[A-Za-z][A-Za-z0-9_.:/-]{3,}", command)
    skip = {
        "echo", "true", "false", "null", "none", "object", "format",
        "system", "host", "this", "that", "with", "from", "into",
        "csp", "test", "cspbtp", "table", "list", "output",
        "param", "argument", "errorAction", "silentlycontinue",
    }
    out: list[str] = []
    for tok in raw:
        low = tok.lower()
        if low in skip:
            continue
        if low in out:
            continue
        out.append(low)
        if len(out) >= 6:
            break
    return out


def _likely_process_image(executor: str) -> str:
    return {
        "powershell": "powershell.exe",
        "pwsh": "pwsh.exe",
        "cmd": "cmd.exe",
        "bash": "bash",
        "sh": "sh",
        "python3": "python3",
    }.get(executor, executor)


# ---------- XQL --------------------------------------------------------------
def _xql_for(tech: Technique, test: TechniqueTest) -> str:
    f = _PROC_FIELDS["xql"]
    image = _likely_process_image(test.executor)
    kws = _extract_keywords(test.command)
    kw_clause = ""
    if kws:
        # any-of match — give the operator a starting set; they tune later.
        parts = " or ".join(f'{f["process_cmd"]} contains "{k}"' for k in kws[:4])
        kw_clause = f"\n    and ({parts})"

    return (
        f"// Cortex XSIAM XQL starter rule for {tech.id} — {tech.name}\n"
        f"// Test: {test.name}\n"
        f"// Auto-generated by CSP — tune field names to your XSIAM data model.\n"
        f"dataset = {f['dataset']}\n"
        f"| filter {f['event_type_proc']}\n"
        f"    and {f['process_name']} ~= \"(?i){re.escape(image)}\""
        f"{kw_clause}\n"
        f"| fields _time, {f['host']}, {f['user']}, "
        f"{f['parent_name']}, {f['process_name']}, {f['process_cmd']}\n"
        f"| sort desc _time"
    )


# ---------- Sigma ------------------------------------------------------------
def _sigma_for(tech: Technique, test: TechniqueTest) -> str:
    image = _likely_process_image(test.executor)
    kws = _extract_keywords(test.command)
    contains_block = ""
    if kws:
        contains_block = (
            "        CommandLine|contains:\n"
            + "\n".join(f"            - '{k}'" for k in kws[:4])
            + "\n"
        )
    return (
        f"title: {tech.id} — {test.name} (CSP starter)\n"
        f"id: csp-{tech.id.lower().replace('.', '-')}-{test.name.replace('_', '-')}\n"
        f"status: experimental\n"
        f"description: |\n"
        f"  Starter Sigma rule for {tech.name}. Generated from CSP catalog.\n"
        f"  Tune field names + severity before deploying.\n"
        f"author: CSP\n"
        f"tags:\n"
        f"  - attack.{tech.tactic.replace('-', '_')}\n"
        f"  - attack.{tech.id.lower()}\n"
        f"logsource:\n"
        f"  category: process_creation\n"
        f"  product: {'windows' if test.executor in ('powershell','pwsh','cmd') else 'linux'}\n"
        f"detection:\n"
        f"    selection:\n"
        f"        Image|endswith: '\\\\{image}' if windows else '{image}'\n"
        f"{contains_block}"
        f"    condition: selection\n"
        f"level: medium\n"
        f"falsepositives:\n"
        f"  - legitimate admin activity matching the same command pattern"
    )


# ---------- Splunk SPL -------------------------------------------------------
def _spl_for(tech: Technique, test: TechniqueTest) -> str:
    f = _PROC_FIELDS["spl"]
    image = _likely_process_image(test.executor)
    kws = _extract_keywords(test.command)
    kw_clause = ""
    if kws:
        kw_clause = " (" + " OR ".join(f'{f["process_cmd"]}="*{k}*"' for k in kws[:4]) + ")"

    return (
        f"# Splunk SPL starter rule for {tech.id} — {tech.name}\n"
        f"# Test: {test.name}\n"
        f"# Tune index/sourcetype + field names to your environment.\n"
        f"{f['dataset']} {f['event_type_proc']}\n"
        f"  {f['process_name']}=\"*{image}*\"{kw_clause}\n"
        f"| table _time {f['host']} {f['user']} "
        f"{f['parent_name']} {f['process_name']} {f['process_cmd']}\n"
        f"| sort - _time"
    )


# ---------- public API -------------------------------------------------------
def generate_rule(
    technique_id: str, test_name: str, rule_format: str = "xql"
) -> DetectionRule:
    rule_format = rule_format.lower()
    if rule_format not in SUPPORTED_RULE_FORMATS:
        raise ValueError(
            f"unsupported rule_format {rule_format!r}; "
            f"expected one of: {', '.join(SUPPORTED_RULE_FORMATS)}"
        )

    pair = get_test(technique_id, test_name)
    if pair is None:
        raise LookupError(f"technique/test not found: {technique_id}/{test_name}")
    tech, test = pair

    if rule_format == "xql":
        rule_text = _xql_for(tech, test)
        notes = (
            "XQL — paste into XSIAM › Detection Rules › Custom rules. "
            "Adjust the dataset and field names if your XDR ingest schema differs."
        )
    elif rule_format == "sigma":
        rule_text = _sigma_for(tech, test)
        notes = (
            "Sigma YAML — convert with sigmac/pySigma to your target backend "
            "(Splunk / Elastic / Sentinel / XQL). Tune severity before deploy."
        )
    else:  # spl
        rule_text = _spl_for(tech, test)
        notes = (
            "Splunk SPL — paste into Splunk › Save As › Alert. "
            "Tune index, sourcetype, and field extractions for your environment."
        )

    title = f"{tech.id} / {test.name} ({rule_format.upper()})"
    return DetectionRule(
        technique_id=tech.id,
        test_name=test.name,
        rule_format=rule_format,
        title=title,
        rule=rule_text,
        notes=notes,
    )


def list_rule_formats() -> tuple[str, ...]:
    return SUPPORTED_RULE_FORMATS
